// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyAbroad.Infrastructure.Persistence;

#nullable disable

namespace StudyAbroad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008052916_AddFinancialDetailsAndActivityDuration")]
    partial class AddFinancialDetailsAndActivityDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyAbroad.Domain.Entities.AiCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_calls");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ai_calls_created_at");

                    b.ToTable("ai_calls", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_analysis_results");

                    b.HasIndex("StudentProfileId", "Kind", "CreatedAt")
                        .HasDatabaseName("ix_analysis_results_student_profile_id_kind_created_at");

                    b.ToTable("analysis_results", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id")
                        .HasName("pk_app_settings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_app_settings_key");

                    b.ToTable("app_settings", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.ToTable("audit_logs", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("review_status");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("sources_json");

                    b.Property<string>("Step")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("step");

                    b.Property<string>("SuggestedCentersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_centers_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ReviewStatus")
                        .HasDatabaseName("ix_chat_messages_review_status");

                    b.HasIndex("ChatSessionId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_chat_session_id_created_at");

                    b.ToTable("chat_messages", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("current_step");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<string>("StudyLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_chat_sessions_skill_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_chat_sessions_user_id_created_at");

                    b.ToTable("chat_sessions", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<string>("PolicyVersion")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("policy_version");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_consents");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_consents_user_id_purpose");

                    b.ToTable("consents", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.EvalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("expected_answer");

                    b.Property<string>("ExpectedSourcesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("expected_sources_json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("question");

                    b.Property<string>("StudyLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_eval_cases");

                    b.ToTable("eval_cases", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PassedCases")
                        .HasColumnType("integer")
                        .HasColumnName("passed_cases");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results_json");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TotalCases")
                        .HasColumnType("integer")
                        .HasColumnName("total_cases");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_eval_runs");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_eval_runs_started_at");

                    b.ToTable("eval_runs", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ForumPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_generated");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<Guid?>("ParentPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StudyLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_forum_posts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_forum_posts_user_id");

                    b.HasIndex("ParentPostId", "CreatedAt")
                        .HasDatabaseName("ix_forum_posts_parent_post_id_created_at");

                    b.HasIndex("StudyLevel", "Status")
                        .HasDatabaseName("ix_forum_posts_study_level_status");

                    b.ToTable("forum_posts", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ForumReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<Guid>("ForumPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("forum_post_id");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_forum_reports");

                    b.HasIndex("ForumPostId")
                        .HasDatabaseName("ix_forum_reports_forum_post_id");

                    b.HasIndex("HandledByUserId")
                        .HasDatabaseName("ix_forum_reports_handled_by_user_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_forum_reports_reporter_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_forum_reports_status");

                    b.ToTable("forum_reports", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("doc_type");

                    b.Property<DateTime?>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<DateOnly?>("RetrievedAt")
                        .HasColumnType("date")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_documents");

                    b.HasIndex("VerifiedByUserId")
                        .HasDatabaseName("ix_knowledge_documents_verified_by_user_id");

                    b.HasIndex("Status", "StudyLevel", "DocType")
                        .HasDatabaseName("ix_knowledge_documents_status_study_level_doc_type");

                    b.ToTable("knowledge_documents", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<bool>("SharedProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("shared_profile");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudyCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_center_id");

                    b.Property<string>("StudyLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("ConsentId")
                        .HasDatabaseName("ix_leads_consent_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_leads_user_id");

                    b.HasIndex("StudyCenterId", "Status")
                        .HasDatabaseName("ix_leads_study_center_id_status");

                    b.ToTable("leads", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("link_url");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("ix_notifications_user_id_read_at");

                    b.ToTable("notifications", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.OtpToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_otp_tokens");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_otp_tokens_user_id_purpose");

                    b.ToTable("otp_tokens", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ProfileActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("duration_months");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("ImpactLevel")
                        .HasColumnType("integer")
                        .HasColumnName("impact_level");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ongoing");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Organization")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization");

                    b.Property<string>("Role")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_profile_activities");

                    b.HasIndex("StudentProfileId", "Kind")
                        .HasDatabaseName("ix_profile_activities_student_profile_id_kind");

                    b.ToTable("profile_activities", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("algorithm_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria_json");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items_json");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recommendations");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_recommendations_student_profile_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_recommendations_user_id_created_at");

                    b.ToTable("recommendations", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.RoadmapStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int?>("MonthsBeforeStart")
                        .HasColumnType("integer")
                        .HasColumnName("months_before_start");

                    b.Property<string>("ResourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resources_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("step_key");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roadmap_steps");

                    b.HasIndex("StudyLevel", "StepKey")
                        .IsUnique()
                        .HasDatabaseName("ix_roadmap_steps_study_level_step_key");

                    b.ToTable("roadmap_steps", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Scholarship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmountUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_usd");

                    b.Property<string>("CoverageType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("coverage_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("EligibilityNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("eligibility_notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinGpa4")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("min_gpa4");

                    b.Property<decimal?>("MinIelts")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("min_ielts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider");

                    b.Property<DateOnly?>("RetrievedAt")
                        .HasColumnType("date")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scholarships");

                    b.HasIndex("StudyLevel")
                        .HasDatabaseName("ix_scholarships_study_level");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_scholarships_university_id");

                    b.ToTable("scholarships", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_key_version");

                    b.ToTable("skills", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Act")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("act");

                    b.Property<decimal?>("AnnualBudgetUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("annual_budget_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentGrade")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_grade");

                    b.Property<string>("CurrentSchool")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("current_school");

                    b.Property<decimal?>("Duolingo")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("duolingo");

                    b.Property<string>("EducationSystem")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("education_system");

                    b.Property<decimal?>("ExtracurricularScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("extracurricular_score");

                    b.Property<string>("FinancialNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("financial_notes");

                    b.Property<string>("FundingSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("funding_source");

                    b.Property<decimal?>("Gmat")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("gmat");

                    b.Property<string>("GradeScale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("grade_scale");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.Property<decimal?>("Gre")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("gre");

                    b.Property<decimal?>("Ielts")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("ielts");

                    b.Property<string>("IntendedMajor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("intended_major");

                    b.Property<decimal?>("MaxExpectedTuitionUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_expected_tuition_usd");

                    b.Property<bool>("NeedsScholarship")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_scholarship");

                    b.Property<string>("OtherTestsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("other_tests_json");

                    b.Property<decimal?>("OverallGpa")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_gpa");

                    b.Property<List<string>>("PreferredStates")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_states");

                    b.Property<string>("RoadmapProgressJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("roadmap_progress_json");

                    b.Property<decimal?>("Sat")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("sat");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_level");

                    b.Property<decimal?>("Toefl")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("toefl");

                    b.Property<string>("TranscriptFileUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("transcript_file_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_user_id");

                    b.ToTable("student_profiles", "app", t =>
                        {
                            t.HasCheckConstraint("ck_student_profiles_extracurricular_score", "extracurricular_score IS NULL OR extracurricular_score BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.StudyCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<List<string>>("Services")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("services");

                    b.Property<List<string>>("StudyLevels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("study_levels");

                    b.Property<DateOnly?>("SurveyedAt")
                        .HasColumnType("date")
                        .HasColumnName("surveyed_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("unverified")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_study_centers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_study_centers_code");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_study_centers_owner_user_id");

                    b.HasIndex("VerifiedByUserId")
                        .HasDatabaseName("ix_study_centers_verified_by_user_id");

                    b.ToTable("study_centers", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.TargetSchool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_target_schools");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_target_schools_university_id");

                    b.HasIndex("UserId", "UniversityId")
                        .IsUnique()
                        .HasDatabaseName("ix_target_schools_user_id_university_id");

                    b.ToTable("target_schools", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.TranscriptScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Credits")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("credits");

                    b.Property<string>("RawScore")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("raw_score");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("term_name");

                    b.Property<int>("TermOrder")
                        .HasColumnType("integer")
                        .HasColumnName("term_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transcript_scores");

                    b.HasIndex("StudentProfileId", "TermOrder")
                        .HasDatabaseName("ix_transcript_scores_student_profile_id_term_order");

                    b.ToTable("transcript_scores", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AcceptanceRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("acceptance_rate");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Control")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("control");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InternationalStudentCount")
                        .HasColumnType("integer")
                        .HasColumnName("international_student_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_universities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_universities_code");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_universities_state");

                    b.ToTable("universities", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.UniversityOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("academic_year");

                    b.Property<decimal?>("AvgGpa4")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("avg_gpa4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeadlinesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("deadlines_json");

                    b.Property<decimal?>("FeesUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("fees_usd");

                    b.Property<decimal?>("LivingUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("living_usd");

                    b.Property<List<string>>("Majors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("majors");

                    b.Property<decimal?>("MinDuolingo")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("min_duolingo");

                    b.Property<decimal?>("MinGpa4")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("min_gpa4");

                    b.Property<decimal?>("MinIelts")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("min_ielts");

                    b.Property<decimal?>("MinToefl")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("min_toefl");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("RetrievedAt")
                        .HasColumnType("date")
                        .HasColumnName("retrieved_at");

                    b.Property<int?>("Sat25")
                        .HasColumnType("integer")
                        .HasColumnName("sat25");

                    b.Property<int?>("Sat75")
                        .HasColumnType("integer")
                        .HasColumnName("sat75");

                    b.Property<string>("SatPolicy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sat_policy");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.Property<List<string>>("StemMajors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("stem_majors");

                    b.Property<string>("StudyLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("study_level");

                    b.Property<decimal?>("TuitionUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tuition_usd");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_university_offerings");

                    b.HasIndex("UniversityId", "StudyLevel")
                        .IsUnique()
                        .HasDatabaseName("ix_university_offerings_university_id_study_level");

                    b.ToTable("university_offerings", "app", t =>
                        {
                            t.HasCheckConstraint("ck_university_offerings_avg_gpa4", "avg_gpa4 IS NULL OR avg_gpa4 BETWEEN 0 AND 4");

                            t.HasCheckConstraint("ck_university_offerings_sat_range", "(sat25 IS NULL OR sat25 BETWEEN 400 AND 1600) AND (sat75 IS NULL OR sat75 BETWEEN 400 AND 1600) AND (sat25 IS NULL OR sat75 IS NULL OR sat25 <= sat75)");
                        });
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("ParentAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("parent_acknowledged");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_user_sessions_token_hash");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_user_sessions_user_id_is_revoked");

                    b.ToTable("user_sessions", "app");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_results_student_profiles_student_profile_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_chat_session_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_sessions_skills_skill_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Consent", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consents_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ForumPost", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.ForumPost", null)
                        .WithMany()
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_forum_posts_forum_posts_parent_post_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_forum_posts_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ForumReport", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.ForumPost", null)
                        .WithMany()
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_reports_forum_posts_forum_post_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_forum_reports_users_handled_by_user_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_reports_users_reporter_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_knowledge_documents_users_verified_by_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Lead", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.Consent", null)
                        .WithMany()
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leads_consents_consent_id");

                    b.HasOne("StudyAbroad.Domain.Entities.StudyCenter", null)
                        .WithMany()
                        .HasForeignKey("StudyCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leads_study_centers_study_center_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leads_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Notification", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.OtpToken", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otp_tokens_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.ProfileActivity", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_activities_student_profiles_student_profile_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recommendations_student_profiles_student_profile_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.Scholarship", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_scholarships_universities_university_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.StudyCenter", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_study_centers_users_owner_user_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_study_centers_users_verified_by_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.TargetSchool", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_schools_universities_university_id");

                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_schools_users_user_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.TranscriptScore", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transcript_scores_student_profiles_student_profile_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.UniversityOffering", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_university_offerings_universities_university_id");
                });

            modelBuilder.Entity("StudyAbroad.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("StudyAbroad.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
